#!/bin/sh

# Cloud backup of Dharma
# Using rclone to sync to an s3 bucket
# #### Bacup on s3 using rclone sync ******

# Backup of posgre database archives for Tomcat
echo "*** Backup **************************************"
echo "XNAT-DB database directory backup on s3:fab-dharma-backup"
echo "rclone sync of archive STARTED on" `date`
echo "**   ************************************   ****"
echo "Backing up XNAT-DB/backup directory"
/usr/bin/rclone sync /data/XNAT-DB/backup/ s3remote:fab-dharma-backup/XNAT-DB/backup
echo "rclone sync of archive FINISHED on" `date`
echo "************************************************"
