#!/bin/sh

RSYNC=/usr/bin/rsync 
SSH=/usr/bin/ssh 
KEY=/home/lab-mfc/cron/xnat-rsync-key 
RUSER=xnat 
RHOST=drobo02 
RPATH=/mnt/DroboFS/home/xnat/backups/XNAT-DB
LPATH=/home/lab-mfc/XNAT-DB/archive

$RSYNC -azh -e "$SSH -i $KEY" $LPATH $RUSER@$RHOST:$RPATH
