#!/bin/sh

RSYNC=/usr/bin/rsync
SSH=/usr/bin/ssh
KEY=/home/xnat/cron/dharma-rsync-key
RUSER=xnat
RHOST=drobo02
RPATH=/mnt/DroboFS/home/xnat/backups/XNAT-DB
LPATH=/data/XNAT-DB/prearchive

$RSYNC -az -e "$SSH -i $KEY" $LPATH $RUSER@$RHOST:$RPATH
