#!/bin/sh

RSYNC=/usr/bin/rsync 
SSH=/usr/bin/ssh 
KEY=/home/lab-mfc/cron/xnat-rsync-key 
RUSER=lab-mfc 
RHOST=drobo02 
LCRONPATH=/home/lab-mfc/cron

# #### Beginnig of bacup on Drobo02 using rsync
echo "*************************************************"
echo "XNAT-DB databese directory backup on Drobo02"
echo "rsync STARTED on" `date`

# rsync-archiveOnDrobo02-backup
echo "Backing up XNAT-DB/archive directory"
$LCRONPATH/rsync-archiveOnDrobo02-backup
echo "***************************************"
# rsync-cacheOnDrobo02-backup
echo "Backing up XNAT-DB/cache directory"
$LCRONPATH/rsync-cacheOnDrobo02-backup
echo "***************************************"
# rsync-ftpOnDrobo02-backup
echo "Backing up XANT-DB/ftp directory"
$LCRONPATH/rsync-ftpOnDrobo02-backup
echo "***************************************"
# rsync-prearchiveOnDrobo02-backup
echo "Backing up XNAT-DB/prearchive directory"
$LCRONPATH/rsync-prearchiveOnDrobo02-backup
echo "***************************************"

# #### End bacup on Drobo02 using rsync
echo "rsync ENDED on" `date`
echo "***** *****************  ****************** *****"
