#!/bin/sh

# This are the new identifiers for the new Dell server Apr 2016
RCLONE=/usr/bin/rclone 
SSH=/usr/bin/ssh
RHOST=drobo02 
LCRONPATH=/home/xnat/cron

# Using rclone to synt to an s3 bucket
#

# Backing up dharma /data/XNAT-DB/prearchive
rclone sync /data/XNAT-DB/prearchive/ s3remote:fab-dharma-backup/XNAT-DB/prearchive

# Backing up dharma /data/XNAT-DB/cache
rclone sync /data/XNAT-DB/cache/ s3remote:fab-dharma-backup/XNAT-DB/cache
